version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
